version: "3.9"

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/src/ap
      - /usr/src/app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:80
    restart: always
    depends_on:
      - backend

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306" 
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
